#+TITLE: Clover

* Deprecated

I've replaced this electron-based approach with a Tauri-based one in [[https://github.com/russmatney/clove][russmatney/clove]].

Discussed here:

- [[https://danger.russmatney.com/daily/2022-10-18.html][2022-10-18 daily note]]
- [[https://danger.russmatney.com/note/tauri_as_a_simple_native_web_view.html][Tauri as a simple native webview]]

* Clover

Clover is a Clojurescript-based "Overlay" tool, intended to support transparent web
overlays while streaming to Twitch.

Initially implemented to support a floating transparent webview.

* Build and Run
To build the node-script:

#+BEGIN_SRC sh
yarn install # yin
shadow-cljs watch cli
#+END_SRC

This builds a ~clover.js~ in the root of the directory, which can then be
passed to electron via:

#+begin_src sh
yarn run electron clover.js <url> <app-title>
#+end_src

~<url>~ the page to load from electron.

~<app-title>~ will be set in the title as ~clover/<app-title>~, which can be
used as a hook from your window manager.

* Develop locally
~cider-jack-in-cljs~ and select ~:cli~ as the build to get things started.

Alternatively, run ~shadow-cljs watch cli~, and connect from your editor.

Once there is a build, you can run ~yrun clover <some-title> <some-url>~ on the
command line to start up a JS runtime, which is required before you can start
evaluating commands.
